import AppKit
import Foundation

private struct PasteboardArchive: Codable {
    let items: [[String: Data]]
}

private enum QAError: Error {
    case invalidArguments
    case unsafeBackupPath
    case backupAlreadyExists
    case pasteboardWriteFailed
}

private let sourceType = "org.nspasteboard.source"
private let remoteType = "com.apple.is-remote-clipboard"

private func backupURL(_ argument: String) throws -> URL {
    let url = URL(fileURLWithPath: argument).standardizedFileURL
    guard url.path.hasPrefix("/private/tmp/") || url.path.hasPrefix("/tmp/") else {
        throw QAError.unsafeBackupPath
    }
    return url
}

private func backupPasteboard(to url: URL) throws {
    guard !FileManager.default.fileExists(atPath: url.path) else {
        throw QAError.backupAlreadyExists
    }
    let items = NSPasteboard.general.pasteboardItems?.map { item in
        Dictionary(
            uniqueKeysWithValues: item.types.compactMap { type in
                item.data(forType: type).map { (type.rawValue, $0) }
            }
        )
    } ?? []
    let encoded = try PropertyListEncoder().encode(PasteboardArchive(items: items))
    guard FileManager.default.createFile(
        atPath: url.path,
        contents: encoded,
        attributes: [.posixPermissions: 0o600]
    ) else {
        throw QAError.pasteboardWriteFailed
    }
}

private func restorePasteboard(from url: URL) throws {
    let encoded = try Data(contentsOf: url)
    let archive = try PropertyListDecoder().decode(PasteboardArchive.self, from: encoded)
    let items = archive.items.map { archived -> NSPasteboardItem in
        let item = NSPasteboardItem()
        for (type, data) in archived {
            item.setData(data, forType: NSPasteboard.PasteboardType(type))
        }
        return item
    }
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    guard items.isEmpty || pasteboard.writeObjects(items) else {
        throw QAError.pasteboardWriteFailed
    }
    try FileManager.default.removeItem(at: url)
}

private func writeSyntheticScenario(_ scenario: String) throws {
    let item = NSPasteboardItem()
    item.setString(
        "copy-stack synthetic qa \(scenario)",
        forType: .string
    )

    let markers: [(String, Data)]
    switch scenario {
    case "plain":
        markers = []
    case "source-empty":
        markers = [(sourceType, Data())]
    case "source-valid":
        markers = [(sourceType, Data("com.example.synthetic".utf8))]
    case "remote":
        markers = [(remoteType, Data())]
    case "transient":
        markers = [("org.nspasteboard.TransientType", Data())]
    case "autogenerated":
        markers = [("org.nspasteboard.AutoGeneratedType", Data())]
    case "concealed":
        markers = [("org.nspasteboard.ConcealedType", Data())]
    case "onepassword":
        markers = [("com.agilebits.onepassword", Data("synthetic-marker".utf8))]
    default:
        throw QAError.invalidArguments
    }
    for (type, data) in markers {
        item.setData(data, forType: NSPasteboard.PasteboardType(type))
    }

    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    guard pasteboard.writeObjects([item]) else {
        throw QAError.pasteboardWriteFailed
    }
}

private func inspectSyntheticPasteboard() throws {
    let pasteboard = NSPasteboard.general
    let item = pasteboard.pasteboardItems?.first
    let types = item?.types.map(\.rawValue).sorted() ?? []
    let sourceData = item?.data(forType: NSPasteboard.PasteboardType(sourceType))
    let sourceValue: Any =
        sourceData.flatMap { String(data: $0, encoding: .utf8) } ?? NSNull()
    let result: [String: Any] = [
        "types": types,
        "source_present": sourceData != nil,
        "source_value": sourceValue,
        "remote_present": item?.data(forType: NSPasteboard.PasteboardType(remoteType)) != nil,
        "item_count": pasteboard.pasteboardItems?.count ?? 0,
    ]
    let encoded = try JSONSerialization.data(withJSONObject: result, options: [.sortedKeys])
    FileHandle.standardOutput.write(encoded)
    FileHandle.standardOutput.write(Data([0x0a]))
}

do {
    let arguments = Array(CommandLine.arguments.dropFirst())
    guard let command = arguments.first else {
        throw QAError.invalidArguments
    }
    switch command {
    case "backup" where arguments.count == 2:
        try backupPasteboard(to: backupURL(arguments[1]))
    case "restore" where arguments.count == 2:
        try restorePasteboard(from: backupURL(arguments[1]))
    case "write" where arguments.count == 2:
        try writeSyntheticScenario(arguments[1])
    case "inspect" where arguments.count == 1:
        try inspectSyntheticPasteboard()
    default:
        throw QAError.invalidArguments
    }
} catch {
    FileHandle.standardError.write(Data("qa-pasteboard: operation failed\n".utf8))
    exit(2)
}
