use copy_event_listener::event::{Data, Event};
use std::fmt;

pub const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
pub const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
pub const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";
pub const SOURCE_TYPE: &str = "org.nspasteboard.source";

pub const LEGACY_TRANSIENT_TYPE: &str = "de.petermaurer.TransientPasteboardType";
pub const TYPEIT4ME_CLIPPING_TYPE: &str = "com.typeit4me.clipping";
pub const PASTEBOARD_GENERATOR_TYPE: &str = "Pasteboard generator type";
pub const ONEPASSWORD_TYPE: &str = "com.agilebits.onepassword";
pub const REMOTE_CLIPBOARD_TYPE: &str = "com.apple.is-remote-clipboard";

const TRANSIENT_TYPES: [&str; 4] = [
    TRANSIENT_TYPE,
    LEGACY_TRANSIENT_TYPE,
    TYPEIT4ME_CLIPPING_TYPE,
    PASTEBOARD_GENERATOR_TYPE,
];
const CONCEALED_TYPES: [&str; 2] = [CONCEALED_TYPE, ONEPASSWORD_TYPE];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HistoryDisposition {
    Record,
    Skip(SkipReason),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SkipReason {
    Concealed,
    Transient,
    AutoGenerated,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct PasteboardMetadata {
    /// The strict UTF-8 payload of `org.nspasteboard.source`.
    ///
    /// `Some("")` is distinct from `None`: an empty source marker explicitly
    /// means that the source is unknown, while `None` means that the marker was
    /// absent or its payload was not valid UTF-8.
    pub source_bundle_id: Option<String>,
    pub is_remote_clipboard: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PasteboardAssessment {
    pub disposition: HistoryDisposition,
    pub metadata: PasteboardMetadata,
}

impl PasteboardAssessment {
    pub fn should_record(&self) -> bool {
        self.disposition == HistoryDisposition::Record
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RestorePreparationError {
    EmptyEvent,
}

impl fmt::Display for RestorePreparationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyEvent => formatter.write_str("clipboard event has no pasteboard items"),
        }
    }
}

impl std::error::Error for RestorePreparationError {}

/// Applies the NSPasteboard.org history policy to the complete clipboard event.
///
/// Marker detection is based only on the presence of exact type names across
/// all pasteboard items. Payload bytes are not inspected for skip markers. The
/// source payload is parsed only after the event has been accepted for history,
/// so a concealed, transient, or autogenerated event is rejected without
/// reading any marker payload.
pub fn assess_event(event: &Event) -> PasteboardAssessment {
    let disposition = if event_has_any_type(event, &CONCEALED_TYPES) {
        HistoryDisposition::Skip(SkipReason::Concealed)
    } else if event_has_any_type(event, &TRANSIENT_TYPES) {
        HistoryDisposition::Skip(SkipReason::Transient)
    } else if event_has_type(event, AUTO_GENERATED_TYPE) {
        HistoryDisposition::Skip(SkipReason::AutoGenerated)
    } else {
        HistoryDisposition::Record
    };

    let metadata = if disposition == HistoryDisposition::Record {
        PasteboardMetadata {
            source_bundle_id: source_bundle_id(event),
            is_remote_clipboard: is_remote_clipboard(event),
        }
    } else {
        PasteboardMetadata::default()
    };

    PasteboardAssessment {
        disposition,
        metadata,
    }
}

/// Returns the first source marker as strict UTF-8, preserving an empty string.
///
/// If the first source marker is malformed, the source is treated as unknown.
/// Later source markers are deliberately ignored because the protocol defines
/// one source for the pasteboard contents and conflicting markers are
/// ambiguous.
pub fn source_bundle_id(event: &Event) -> Option<String> {
    event_data(event)
        .find(|data| data.r#type == SOURCE_TYPE)
        .and_then(|data| String::from_utf8(data.data.clone()).ok())
}

/// Reports remote clipboard provenance by marker presence, not marker payload.
pub fn is_remote_clipboard(event: &Event) -> bool {
    event_has_type(event, REMOTE_CLIPBOARD_TYPE)
}

/// Canonicalizes protocol provenance before restoring a stored event.
///
/// Existing source and remote markers are removed from every item. Exactly one
/// source marker is then placed on the first item, using the stored bundle
/// identifier or an empty payload when the source is unknown. A single empty
/// remote marker is also placed on the first item when the stored event was
/// captured from another device.
pub fn prepare_event_for_restore(
    mut event: Event,
    source_bundle_id: Option<&str>,
    is_remote_clipboard: bool,
) -> Result<Event, RestorePreparationError> {
    if event.items.is_empty() {
        return Err(RestorePreparationError::EmptyEvent);
    }

    for item in &mut event.items {
        item.data_list
            .retain(|data| data.r#type != SOURCE_TYPE && data.r#type != REMOTE_CLIPBOARD_TYPE);
    }

    let first_item = &mut event.items[0];
    first_item.data_list.push(Data {
        r#type: SOURCE_TYPE.to_string(),
        data: source_bundle_id.unwrap_or_default().as_bytes().to_vec(),
    });
    if is_remote_clipboard {
        first_item.data_list.push(Data {
            r#type: REMOTE_CLIPBOARD_TYPE.to_string(),
            data: Vec::new(),
        });
    }

    Ok(event)
}

fn event_has_any_type(event: &Event, data_types: &[&str]) -> bool {
    event_data(event).any(|data| data_types.iter().any(|data_type| data.r#type == *data_type))
}

fn event_has_type(event: &Event, data_type: &str) -> bool {
    event_data(event).any(|data| data.r#type == data_type)
}

fn event_data(event: &Event) -> impl Iterator<Item = &Data> {
    event.items.iter().flat_map(|item| item.data_list.iter())
}

#[cfg(test)]
mod tests {
    use super::*;
    use copy_event_listener::event::Item;

    fn data(data_type: &str, payload: &[u8]) -> Data {
        Data {
            r#type: data_type.to_string(),
            data: payload.to_vec(),
        }
    }

    fn event(data_list: Vec<Data>) -> Event {
        Event {
            items: vec![Item { data_list }],
        }
    }

    fn multi_item_event(data_lists: Vec<Vec<Data>>) -> Event {
        Event {
            items: data_lists
                .into_iter()
                .map(|data_list| Item { data_list })
                .collect(),
        }
    }

    fn text_data() -> Data {
        data("public.utf8-plain-text", b"synthetic protocol fixture")
    }

    fn count_type(event: &Event, data_type: &str) -> usize {
        event_data(event)
            .filter(|data| data.r#type == data_type)
            .count()
    }

    #[test]
    fn policy_table_covers_universal_and_proprietary_markers() {
        struct Case {
            name: &'static str,
            marker: Option<&'static str>,
            payload: &'static [u8],
            expected_disposition: HistoryDisposition,
            expected_remote: bool,
        }

        let cases = [
            Case {
                name: "ordinary content",
                marker: None,
                payload: b"",
                expected_disposition: HistoryDisposition::Record,
                expected_remote: false,
            },
            Case {
                name: "universal transient with empty payload",
                marker: Some(TRANSIENT_TYPE),
                payload: b"",
                expected_disposition: HistoryDisposition::Skip(SkipReason::Transient),
                expected_remote: false,
            },
            Case {
                name: "universal transient with non-empty payload",
                marker: Some(TRANSIENT_TYPE),
                payload: b"ignored",
                expected_disposition: HistoryDisposition::Skip(SkipReason::Transient),
                expected_remote: false,
            },
            Case {
                name: "legacy TextExpander or Butler transient",
                marker: Some(LEGACY_TRANSIENT_TYPE),
                payload: b"",
                expected_disposition: HistoryDisposition::Skip(SkipReason::Transient),
                expected_remote: false,
            },
            Case {
                name: "TypeIt4Me transient",
                marker: Some(TYPEIT4ME_CLIPPING_TYPE),
                payload: b"ignored",
                expected_disposition: HistoryDisposition::Skip(SkipReason::Transient),
                expected_remote: false,
            },
            Case {
                name: "Typinator generator transient",
                marker: Some(PASTEBOARD_GENERATOR_TYPE),
                payload: b"",
                expected_disposition: HistoryDisposition::Skip(SkipReason::Transient),
                expected_remote: false,
            },
            Case {
                name: "autogenerated",
                marker: Some(AUTO_GENERATED_TYPE),
                payload: b"ignored",
                expected_disposition: HistoryDisposition::Skip(SkipReason::AutoGenerated),
                expected_remote: false,
            },
            Case {
                name: "universal concealed",
                marker: Some(CONCEALED_TYPE),
                payload: b"",
                expected_disposition: HistoryDisposition::Skip(SkipReason::Concealed),
                expected_remote: false,
            },
            Case {
                name: "1Password concealed",
                marker: Some(ONEPASSWORD_TYPE),
                payload: b"ignored",
                expected_disposition: HistoryDisposition::Skip(SkipReason::Concealed),
                expected_remote: false,
            },
            Case {
                name: "remote clipboard remains recordable",
                marker: Some(REMOTE_CLIPBOARD_TYPE),
                payload: b"ignored",
                expected_disposition: HistoryDisposition::Record,
                expected_remote: true,
            },
        ];

        for case in cases {
            let mut data_list = vec![text_data()];
            if let Some(marker) = case.marker {
                data_list.push(data(marker, case.payload));
            }

            let assessment = assess_event(&event(data_list));
            assert_eq!(
                assessment.disposition, case.expected_disposition,
                "{}",
                case.name
            );
            assert_eq!(
                assessment.metadata.is_remote_clipboard, case.expected_remote,
                "{}",
                case.name
            );
        }
    }

    #[test]
    fn policy_scans_every_item_and_uses_strict_precedence() {
        struct Case {
            name: &'static str,
            markers: &'static [&'static str],
            expected: HistoryDisposition,
        }

        let cases = [
            Case {
                name: "transient overrides autogenerated",
                markers: &[AUTO_GENERATED_TYPE, TRANSIENT_TYPE],
                expected: HistoryDisposition::Skip(SkipReason::Transient),
            },
            Case {
                name: "concealed overrides transient",
                markers: &[TRANSIENT_TYPE, CONCEALED_TYPE],
                expected: HistoryDisposition::Skip(SkipReason::Concealed),
            },
            Case {
                name: "1Password overrides autogenerated",
                markers: &[AUTO_GENERATED_TYPE, ONEPASSWORD_TYPE],
                expected: HistoryDisposition::Skip(SkipReason::Concealed),
            },
            Case {
                name: "remote does not override transient",
                markers: &[REMOTE_CLIPBOARD_TYPE, LEGACY_TRANSIENT_TYPE],
                expected: HistoryDisposition::Skip(SkipReason::Transient),
            },
            Case {
                name: "source does not override concealed",
                markers: &[SOURCE_TYPE, CONCEALED_TYPE],
                expected: HistoryDisposition::Skip(SkipReason::Concealed),
            },
        ];

        for case in cases {
            let mut items = vec![vec![text_data()]];
            items.extend(
                case.markers
                    .iter()
                    .map(|marker| vec![data(marker, b"synthetic")]),
            );
            let assessment = assess_event(&multi_item_event(items));

            assert_eq!(assessment.disposition, case.expected, "{}", case.name);
            assert_eq!(
                assessment.metadata,
                PasteboardMetadata::default(),
                "{} must not extract metadata from a skipped event",
                case.name
            );
        }
    }

    #[test]
    fn source_parsing_is_strict_and_preserves_explicit_empty_values() {
        struct Case {
            name: &'static str,
            data_lists: Vec<Vec<Data>>,
            expected: Option<&'static str>,
        }

        let cases = [
            Case {
                name: "missing source",
                data_lists: vec![vec![text_data()]],
                expected: None,
            },
            Case {
                name: "empty source is explicit unknown",
                data_lists: vec![vec![text_data(), data(SOURCE_TYPE, b"")]],
                expected: Some(""),
            },
            Case {
                name: "valid bundle identifier",
                data_lists: vec![vec![
                    text_data(),
                    data(SOURCE_TYPE, b"com.example.SourceApp"),
                ]],
                expected: Some("com.example.SourceApp"),
            },
            Case {
                name: "invalid UTF-8 is unknown",
                data_lists: vec![vec![text_data(), data(SOURCE_TYPE, &[0xff, 0xfe])]],
                expected: None,
            },
            Case {
                name: "source can appear on a later item",
                data_lists: vec![
                    vec![text_data()],
                    vec![data(SOURCE_TYPE, b"com.example.SecondItem")],
                ],
                expected: Some("com.example.SecondItem"),
            },
            Case {
                name: "first source marker wins",
                data_lists: vec![
                    vec![text_data(), data(SOURCE_TYPE, b"com.example.First")],
                    vec![data(SOURCE_TYPE, b"com.example.Second")],
                ],
                expected: Some("com.example.First"),
            },
            Case {
                name: "malformed first source is not replaced by a later marker",
                data_lists: vec![
                    vec![text_data(), data(SOURCE_TYPE, &[0xff])],
                    vec![data(SOURCE_TYPE, b"com.example.Second")],
                ],
                expected: None,
            },
        ];

        for case in cases {
            let event = multi_item_event(case.data_lists);
            assert_eq!(
                source_bundle_id(&event).as_deref(),
                case.expected,
                "{}",
                case.name
            );
            assert_eq!(
                assess_event(&event).metadata.source_bundle_id.as_deref(),
                case.expected,
                "{}",
                case.name
            );
        }
    }

    #[test]
    fn remote_detection_uses_presence_across_items_and_ignores_payload() {
        for payload in [b"".as_slice(), b"non-empty".as_slice()] {
            let event = multi_item_event(vec![
                vec![text_data()],
                vec![data(REMOTE_CLIPBOARD_TYPE, payload)],
            ]);

            assert!(is_remote_clipboard(&event));
            let assessment = assess_event(&event);
            assert!(assessment.should_record());
            assert!(assessment.metadata.is_remote_clipboard);
        }
    }

    #[test]
    fn similar_or_differently_cased_type_names_are_not_protocol_markers() {
        for data_type in [
            "org.nspasteboard.TransientType.extra",
            "org.nspasteboard.transienttype",
            "com.agilebits.onepassword.backup",
            "com.apple.is-remote-clipboard-extra",
        ] {
            let assessment = assess_event(&event(vec![text_data(), data(data_type, b"")]));
            assert!(assessment.should_record(), "{data_type}");
            assert_eq!(assessment.metadata, PasteboardMetadata::default());
        }
    }

    #[test]
    fn restore_canonicalizes_existing_source_and_remote_markers() {
        let event = multi_item_event(vec![
            vec![
                text_data(),
                data(SOURCE_TYPE, b"com.example.Stale"),
                data(REMOTE_CLIPBOARD_TYPE, b"stale payload"),
            ],
            vec![
                data("public.html", b"<p>synthetic</p>"),
                data(SOURCE_TYPE, b"com.example.Duplicate"),
                data(REMOTE_CLIPBOARD_TYPE, b"duplicate"),
            ],
        ]);

        let restored =
            prepare_event_for_restore(event, Some("com.example.Original"), true).unwrap();

        assert_eq!(count_type(&restored, SOURCE_TYPE), 1);
        assert_eq!(count_type(&restored, REMOTE_CLIPBOARD_TYPE), 1);
        assert_eq!(
            source_bundle_id(&restored).as_deref(),
            Some("com.example.Original")
        );
        assert!(is_remote_clipboard(&restored));
        assert_eq!(
            restored.items[0].data_list[0].r#type,
            "public.utf8-plain-text"
        );
        assert_eq!(restored.items[1].data_list.len(), 1);
        assert_eq!(restored.items[1].data_list[0].r#type, "public.html");
    }

    #[test]
    fn restore_writes_empty_source_when_source_is_unknown() {
        for source in [None, Some("")] {
            let restored =
                prepare_event_for_restore(event(vec![text_data()]), source, false).unwrap();

            assert_eq!(count_type(&restored, SOURCE_TYPE), 1);
            assert_eq!(source_bundle_id(&restored).as_deref(), Some(""));
            assert!(!is_remote_clipboard(&restored));
        }
    }

    #[test]
    fn restore_removes_remote_marker_when_metadata_is_false() {
        let event = event(vec![text_data(), data(REMOTE_CLIPBOARD_TYPE, b"stale")]);

        let restored = prepare_event_for_restore(event, Some("com.example.Source"), false).unwrap();

        assert_eq!(count_type(&restored, SOURCE_TYPE), 1);
        assert_eq!(count_type(&restored, REMOTE_CLIPBOARD_TYPE), 0);
    }

    #[test]
    fn restore_rejects_events_without_items() {
        let result = prepare_event_for_restore(Event { items: Vec::new() }, None, false);

        assert!(matches!(result, Err(RestorePreparationError::EmptyEvent)));
    }
}
